### PR TITLE
function array_key_first used instead of accessing 0 index, index key…

### PR DESCRIPTION
**Pull request by dineshsailor**
… could be anything

### CODE REVIEW

**Comment by kfirba** [comment]
Thanks a lot for the PR! 

There isn’t any major benefit from doing it.
In fact, if we ever decide to run the rows through some filtering mechanism, your solution will fall short. this is a micro optimization.

thanks again for the PR, but I’m going to close it for now.

**Comment by dineshsailor** [comment]
In my solution I'm passing associate array and this could be a quick fix for me.

**Comment by kfirba** [comment]
It works either way. Doesn’t it work for you?

**Comment by dineshsailor** [comment]
How will it find 0 index with associate array? Its multi dimension array where keys are not integer  and that's reason I have used array_key_first function to get the first key

**Comment by kfirba** [comment]
@dineshsailor I see what you're saying

**Comment by kfirba** [comment]
Completely misunderstood you. Thanks!

**Pull request merged**
